# Generated by Django 6.0.6 on 2026-06-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='movies/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='bookmyapp.userregister')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
