# Generated by Django 6.0.6 on 2026-06-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyapp', '0002_movies_delete_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
